### ISSUE TITLE
Large diffrence in pixel rocauc

### ISSUE THREAD

**Issue by momo1476422482** [byungjae89/SPADE-pytorch#15]
Hello,
I tried your code within the MVCTech dataset (bottle class) and I used all of the train data and a part of the test data. For the image leb=vel AUC ROC, there is no pb but for the pixel level one, I have only got 0.61... I would like to know that if I did sth wrong?

Thans a lot in advance

**Comment by AndSonder** [comment]
Me too!
My bottle class result: 
![image](https://user-images.githubusercontent.com/55493212/183542634-4fc0f5cf-bb87-40e2-86c3-ef42882f85d4.png)

**Comment by hellojun12** [comment]
I'm also having the same problem here. I tried to find the solution for 2days but couldn't reach any close results.

**Comment by mgpadalkar** [comment]
I believe this is happening because of difference in PyTorch versions.

Earlier I tried using:
```
python 3.10.4
torch 1.12.1
torchvision 0.13.1
```
and got these results :disappointed:
![roc_curve](https://user-images.githubusercontent.com/6649096/187244159-9e2daaa7-cb70-40b7-b03b-46d89fa24570.png)


Then I used the environment suggested by @byungjae89 in the readme, viz.,
```
python 3.6.13
torch 1.5.0
torchvision 0.6.0
```
and now the results are as given below (same as expected)! :heart_eyes: :sweat_smile:
![roc_curve](https://user-images.githubusercontent.com/6649096/187246559-93fb3249-ac0d-4226-b3a1-59bb38b5b0f9.png)



Thanks to the following comments:
https://github.com/byungjae89/SPADE-pytorch/issues/6#issue-871820112
https://github.com/byungjae89/MahalanobisAD-pytorch/issues/2#issuecomment-771366404

### How I set my environment?
```
conda create -n spade python=3.6
conda activate spade
conda install pytorch==1.5.0 torchvision==0.6.0 cudatoolkit=10.2 -c pytorch
pip install sklearn matplotlib tqdm
```

**Comment by momo1476422482** [comment]
Thanks a lot for your help  @mgpadalkar!!!

**Comment by detectivelinx** [comment]
> 

I'm confused, why versions results in difference?  Could you help to explain it?

**Comment by wu33learn** [comment]
> > 
> 
> I'm confused, why versions results in difference? Could you help to explain it?

https://github.com/byungjae89/SPADE-pytorch/issues/13
